update to jetty 10
error:
[main] WARN org.eclipse.jetty.servlet.BaseHolder - Unable to load class org.eclipse.jetty.servlet.listener.ELContextCleaner
java.lang.ClassNotFoundException: org.eclipse.jetty.servlet.listener.ELContextCleaner